### ISSUE TITLE
Failing on app launch

### ISSUE THREAD

**Issue by mpentler** [ZbychuButItWasTaken/NOAA_HIRS_Decoder#5]
This app used to work for me, but for some reason now I am having issues:

C:\Users\tehhu\Downloads\NOAA_HIRS_Decoder-1.0.3.1-windows>NOAA_HIRS_Decoder.exe minorFrames.txt
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter 'minorFrames.txt' but no main parameter was defined in your arg class
        at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:954)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:755)
        at com.beust.jcommander.JCommander.parse(JCommander.java:356)
        at com.beust.jcommander.JCommander.parse(JCommander.java:335)
        at sh.surge.NOAA_HIRS_Decoder.Main.main(Main.java:107)

===
The app runs fine without specifying an input file and exits cleanly, but drag/dropping a file or using the cmd line results in this crash. Windows 10, Java 8 JRE is installed

**Comment by mpentler** [comment]
I am a HUGE idiot who doesn't read help switches. Closing.
